project_id = "hodtsmyjqtkjlkburoea"

[functions.sync-mercadolivre]
verify_jwt = false

[functions.parse-catalog]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false

[functions.generate-marketing-text]
verify_jwt = false

[functions.generate-ai-background]
verify_jwt = false

[functions.generate-creative-image]
verify_jwt = false

[functions.identify-part]
verify_jwt = false