ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS weight_kg numeric DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS width_cm numeric DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS height_cm numeric DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS length_cm numeric DEFAULT NULL;